name: CI for Mattermost Plugins

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - name: Set npm to use Python 2
        run: npm config set python /usr/bin/python2.7

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
          
      - name: Restore Go Modules Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          
      - name: Restore NPM Cache
        uses: actions/cache@v3
        with:
          path: webapp/node_modules
          key: npm-${{ hashFiles('webapp/package-lock.json') }}
          
      - name: Install NPM dependencies
        run: cd webapp && npm install --legacy-peer-deps

      - name: Run linters and style checks
        run: make check-style

      - name: Save Go Modules Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: go-mod-${{ hashFiles('**/go.sum') }}
          
      - name: Go mod tidy
        run: go mod tidy -v

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - name: Set npm to use Python 2
        run: npm config set python /usr/bin/python2.7

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install NPM dependencies
        run: cd webapp && npm install --legacy-peer-deps

      - name: Run tests
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - name: Set npm to use Python 2
        run: npm config set python /usr/bin/python2.7

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install NPM dependencies
        run: cd webapp && npm install --legacy-peer-deps

      - name: Build Plugin Bundle
        run: make dist

      - name: Generate Release Notes
        run: |
          printf "Supported Mattermost Server Versions: **$(jq .min_server_version -r < plugin.json)+** \n## Enhancements\n\n## Fixes\n" >> dist/release-notes.md
          if [[ $(git tag -l | wc -l) -eq 1 ]]; then
            git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git rev-list --max-parents=0 HEAD) HEAD >> dist/release-notes.md
          else
            git log --pretty='format:- %h %s' --abbrev-commit --no-decorate --no-color $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)..HEAD >> dist/release-notes.md
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - name: Set npm to use Python 2
        run: npm config set python /usr/bin/python2.7

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Publish Release on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghr -t $GITHUB_TOKEN -u ${{ github.repository_owner }} -r ${{ github.event.repository.name }} -b "$(cat dist/release-notes.md)" -c ${{ github.sha }} -n ${{ github.ref_name }} -delete ${{ github.ref_name }} dist/*.tar.gz
